language: d

matrix:
  include:
    - d: dmd-beta
    - d: dmd-2.074.1
      env: [COVERAGE=true]
    - d: dmd-2.068.2
    - d: ldc-1.2.0
    - d: ldc-1.1.0
    - d: ldc-1.0.0
    - d: dmd-2.073.2
    - d: dmd-2.072.2
    - d: dmd-2.071.2
    - d: dmd-2.070.2
    - d: dmd-2.069.2

sudo: false

script: ./travis.sh
